### ISSUE TITLE
Oracle server

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#103]
Setup an Oracle server environment and connect to the database.

**Comment by AlbertFX91** [comment]
## Created Oracle DB in dev
[Table CARS](https://gyazo.com/b8a33bb18547c63d761332691b2e981b)

## Finally it works!
[Demo](https://gyazo.com/28bbb51aa6fac2f8d3516f7d2dc3b7d2)

## But bad news.
Oracle doesnt provide a public jdbc driver in maven (Thank you Larry). So, it was necessary to instal it manually in the local maven repository of the dev system. After that, it was necessary to add it in the pom.xml
¿What is the problem? If other system try to build the project, it wont find the jdbc :'(
So, just for now, i think we must to install it manually in our systems, just to define de architecture and functionality with different kind of databases. After that, we could remove it from our pom.xml

## How install it dude?
Easy. (?)
First, download the jdbc driver from the oracle's web: 
http://www.oracle.com/technetwork/apps-tech/jdbc-112010-090769.html

Second: Install the ojdbc6.jar driver in our local maven repository: 
`mvnw nstall:install-file -Dfile=<<path to the ojdbc6.jar file>> -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0 -Dpackaging=jar`

## Give me more news
The issue was estimated in 2 points. Ü know what? It was necessary 4'5 hours of our time 😢
