### ISSUE TITLE
Core - Core restructuring

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#280]

**Comment by juagarfer4** [comment]
I am not sure the demos are understandable. I hope they are. Otherwise, you just have to ask!

Demo:
- Not allowing to create a control var if its value is not an integer [(1)](https://gyazo.com/fc2866c6a140d6203e818d5d252dff9e) [(2)](https://gyazo.com/8fdf8bb557ababaf969a86d69437dbf9)
- [Blocking an already existing control var whose value is not an integer](https://gyazo.com/9dd569a4df806e32b371e4ded3a43acf)
