### ISSUE TITLE
Service - API REST call with class mapping

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#61]

**Comment by juagarfer4** [comment]
Man, gotta love parsing.

I've been working with that small books API that we used during the Angular course. If we wanted to use some of the APIs from JSONPlaceholder, the object would be different and there could be some small changes in the parsing process, but that's about it.

[Code](https://gist.github.com/juagarfer4/4c1961f3142466f5824f31c134ae234b)
[Proof](https://gyazo.com/dad5001ca64a435eb55abfd45138e918)

**Comment by AlbertFX91** [comment]
Mmm nice aproximation but i think that i could be a better solution with the parsing.
You are parsing the data using instructions like substring and things like that. Is a solution but i think you need to find a tool to work with json and parse it, avoiding using subtrings and regular expresions, because is a low level problem for us.

**Comment by juagarfer4** [comment]
Finally, I decided to use the JSONPlaceholder format, as I assume that all JSON responses will be similar to that rather than to the Books API. I would say that using class mapping is the best option, but, fortunately, we can choose.

WARNING: pom.xml was updated, so you should Update Maven Project if accessing api-rest-calls branch.

[Source](https://gist.github.com/juagarfer4/7dff776d6bdedaf798010a0349bab4f7)
[Proof](https://gyazo.com/3fec45f36a7a1b91e8a87700c3a83a37)

**Comment by AlbertFX91** [comment]
Perfect!
