### ISSUE TITLE
Backend - Refactor server code

### ISSUE THREAD

**Issue by AlbertFX91** [AlbertFX91/Deccom#66]

**Comment by juagarfer4** [comment]
Finally, it all works and the code has been refactored and explained!

As explained before, I decided to ignore the Books API and focus on JSONPlaceholder. I hope that its format will be quite similar to the ones that we will have to face. I would say that using class mapping is the best solution, but we are fortunate enough to be able to consider both of them.

Since this issue covers pretty much all the other issues, maybe you could just check this one. Maybe.

WARNING: I modified pom.xml, so remember to Update Maven Project if accessing to api-rest-calls.

[Source](https://gist.github.com/juagarfer4/cfcb72e495dfc8359615cd904bd0b42f)
Demo [(1)](https://gyazo.com/78a7efe4aaf24c5ccbc45e0a282d6705) [(2)](https://gyazo.com/78fc224972f8e9cc997498a3cd083d16)

**Comment by AlbertFX91** [comment]
Nice refactor bro, specially the abstraction of the http request call :)
