### ISSUE TITLE
DB calls - Frontend - Form

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#96]
A form to perform database calls must be created.

**Comment by AlbertFX91** [comment]
Hello! This is my first version for query a database. 
ce2b58e236f6291fea237e6c8aefd84501072456
There are a lot of things to do like:
- Print the exact error
- Send the data via POST or PUT instead of GET
- Create a connection before do the query
- Check the SQL syntax before send the data.

[Demo](https://gyazo.com/8b58ec75e62b7725290e4ee2da616c12)

**Comment by juagarfer4** [comment]
Yeah, there's still a lot of work ahead, but I'd say this is a big step! The whole functionality of sending a query and getting a response is on its way. I think it's a huge achievement!
