### ISSUE TITLE
Backend tests for DB calls

### ISSUE THREAD

**Issue by juagarfer4** [AlbertFX91/Deccom#99]
Some JUnit tests for the DB calls functionality must be implemented.

**Comment by AlbertFX91** [comment]
I have write only one test for this module.
2936335224c665da26bbe44249eb85de2309613e
Because this test needs a mysql server running on the dev enviroment, here is the data which is used to test the controller
`Author: {debut=2016-11-23 00:00:00.0, idauthor=1, avgbooks=10.63, name=name-1, age=18}`
[Result](https://gyazo.com/fdb82fe3fe27111a13e8121ddb05339f)

**Comment by juagarfer4** [comment]
Yeah I think it's alright. JHipster doesn't include negative tests by default, so I can't see the point in implementing them as well.
